// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package msgraphconnector.proxies;

public enum ApplicationErrorHandling
{
	Do_Nothing(new java.lang.String[][] { new java.lang.String[] { "en_US", "Do Nothing" }, new java.lang.String[] { "en_GB", "Do Nothing" } }),
	Show_Error_Message(new java.lang.String[][] { new java.lang.String[] { "en_US", "Show Error Message" }, new java.lang.String[] { "en_GB", "Show Error Message" } }),
	Log_Error(new java.lang.String[][] { new java.lang.String[] { "en_US", "Log Error" }, new java.lang.String[] { "en_GB", "Log Error" } }),
	Log_and_Show_Error_Message(new java.lang.String[][] { new java.lang.String[] { "en_US", "Log and Show Error Message" }, new java.lang.String[] { "en_GB", "Log and Show Error Message" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private ApplicationErrorHandling(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_GB");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_GB");
	}
}
