// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package environmentinfo.proxies;

public enum DTAP
{
	Development(new java.lang.String[][] { new java.lang.String[] { "en_US", "" }, new java.lang.String[] { "en_GB", "Development" } }),
	Testing(new java.lang.String[][] { new java.lang.String[] { "en_US", "" }, new java.lang.String[] { "en_GB", "Testing" } }),
	Acceptance(new java.lang.String[][] { new java.lang.String[] { "en_US", "" }, new java.lang.String[] { "en_GB", "Acceptance" } }),
	Production(new java.lang.String[][] { new java.lang.String[] { "en_US", "" }, new java.lang.String[] { "en_GB", "Production" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private DTAP(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_GB");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_GB");
	}
}
