// This file was generated by Mendix Modeler 7.23.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package shelterbox_ui_resources.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the Shelterbox_UI_Resources module

	public static java.lang.String getcontacts_url()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Shelterbox_UI_Resources.contacts_url");
	}

	public static java.lang.String getcontracts_url()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Shelterbox_UI_Resources.contracts_url");
	}

	public static java.lang.String getinventory_url()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Shelterbox_UI_Resources.inventory_url");
	}

	public static java.lang.String getlogistics_url()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Shelterbox_UI_Resources.logistics_url");
	}

	public static java.lang.String getops_url()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Shelterbox_UI_Resources.ops_url");
	}

	public static java.lang.String getproducts_url()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Shelterbox_UI_Resources.products_url");
	}

	public static java.lang.String getshipping_url()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Shelterbox_UI_Resources.shipping_url");
	}
}