// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package shelterbox_ui_resources.proxies;

public class Photo extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Shelterbox_UI_Resources.Photo";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PublicThumbnailPath("PublicThumbnailPath"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		Photo_Account("Shelterbox_UI_Resources.Photo_Account");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Photo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Shelterbox_UI_Resources.Photo"));
	}

	protected Photo(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject photoMendixObject)
	{
		super(context, photoMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("Shelterbox_UI_Resources.Photo", photoMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Shelterbox_UI_Resources.Photo");
	}

	/**
	 * @deprecated Use 'Photo.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static shelterbox_ui_resources.proxies.Photo initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return shelterbox_ui_resources.proxies.Photo.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static shelterbox_ui_resources.proxies.Photo initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new shelterbox_ui_resources.proxies.Photo(context, mendixObject);
	}

	public static shelterbox_ui_resources.proxies.Photo load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return shelterbox_ui_resources.proxies.Photo.initialize(context, mendixObject);
	}

	public static java.util.List<shelterbox_ui_resources.proxies.Photo> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<shelterbox_ui_resources.proxies.Photo> result = new java.util.ArrayList<shelterbox_ui_resources.proxies.Photo>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Shelterbox_UI_Resources.Photo" + xpathConstraint))
			result.add(shelterbox_ui_resources.proxies.Photo.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of Photo_Account
	 */
	public final administration.proxies.Account getPhoto_Account() throws com.mendix.core.CoreException
	{
		return getPhoto_Account(getContext());
	}

	/**
	 * @param context
	 * @return value of Photo_Account
	 */
	public final administration.proxies.Account getPhoto_Account(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administration.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Photo_Account.toString());
		if (identifier != null)
			result = administration.proxies.Account.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Photo_Account
	 * @param photo_account
	 */
	public final void setPhoto_Account(administration.proxies.Account photo_account)
	{
		setPhoto_Account(getContext(), photo_account);
	}

	/**
	 * Set value of Photo_Account
	 * @param context
	 * @param photo_account
	 */
	public final void setPhoto_Account(com.mendix.systemwideinterfaces.core.IContext context, administration.proxies.Account photo_account)
	{
		if (photo_account == null)
			getMendixObject().setValue(context, MemberNames.Photo_Account.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Photo_Account.toString(), photo_account.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final shelterbox_ui_resources.proxies.Photo that = (shelterbox_ui_resources.proxies.Photo) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Shelterbox_UI_Resources.Photo";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
